### PR TITLE
Replace broken MS links

### PR DESCRIPTION
**Pull request by joel-powers**
The broken MS links are replaced by up-to-date ones, used correct apostrophes, & escaped an angle bracket for consistency. Mostly minor stuff.

### CODE REVIEW

**Comment by arthurvr** [comment]
Mind also fixing this in the translations? Thanks a lot for your PR.

**Comment by joel-powers** [comment]
I will take care of the URLs, but someone else will have to handle the link text. Maybe the person(s) who did the translations won't mind fixing that?

I will reach out to them later today to work that out.

**Comment by arthurvr** [comment]
@joel-powers Yeah, you're right. The translations are always kind of a pain to maintain. I'll merge this one and leave the issue open so we can fix the translations later.

**Comment by arthurvr** [comment]
Merged. Thanks!

**Pull request closed without merging**
